print("be, or not ot be: that is the question:")
print("'tis nobler in the mind of suffer")
print("slings and arrows of outrageous fortune,")
print("to take arms against a sea of troubles,")
print("by opposing end them?")